# Generated by Django 3.2.18 on 2023-03-19 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_mentee', models.BooleanField(default=False)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('executive_summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('technical_skills', models.TextField(blank=True, max_length=500, null=True)),
                ('leadership_skills', models.TextField(blank=True, max_length=500, null=True)),
                ('my_achievements', models.TextField(blank=True, max_length=500, null=True)),
                ('my_linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('my_website', models.CharField(blank=True, max_length=250, null=True)),
                ('my_published_articles', models.TextField(blank=True, max_length=500, null=True)),
                ('my_mentors', models.CharField(blank=True, max_length=250, null=True)),
                ('my_inspirational_women', models.CharField(blank=True, max_length=250, null=True)),
                ('testimonials_given', models.TextField(blank=True, max_length=500, null=True)),
                ('testimonials_received', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
