# Generated by Django 3.2.18 on 2023-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_fullname', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('expertise_areas', models.CharField(max_length=250)),
                ('contact_website', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_bio', models.TextField(max_length=500)),
                ('why_mentor', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
