# Generated by Django 3.2.18 on 2023-03-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='expertise_areas',
            new_name='areas_of_expertise',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='why_mentor',
            new_name='why_you_want_to_become_a_mentor',
        ),
    ]
