# Generated by Django 3.2.18 on 2023-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='linkin',
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
